### PR TITLE
Describe development process

### PR DESCRIPTION
**Pull request by thinkh**
Since we changed the new repository structure and dependency management for Phovea repositories, we should describe how it works.

### CODE REVIEW

**Comment by thinkh** [comment]
@sgratzl Please check if the first draft is correct.  There is some information missing about publishing on NPM and/or pip registries. Please add further commands about steps that can be done using the phovea generator.

**Comment by sgratzl** [comment]
looks good, thx

btw. current hiearchy in pseudo notation:
```
server
 data_redis
 data_mongo
 data_hdf
 data_sql
core
 d3
  vis
 vis_lineup
 ui
server+core
 security_flask
d3+ui
 importer
security_flask+ui+vis
 clue
core+redis
 processing_queue
```

**Comment by thinkh** [comment]
Thanks. I added the dependency hierarchy to the document.

**Comment by mccalluc** [comment]
I could be misunderstanding the flow, but if versions are pinned in the release branch and then merged back to the dev branch as well as master, is there then a follow-up commit in dev to un-pin these? Perhaps modify that scheme so that release branches are only used for pinning dependencies, and are only merged into master?

Perhaps rather than totally unpinned dependencies in dev, use "^"? I worry that with this scheme we'll be back in a place where less active contributors working off of dev may be working with outdated local dependencies on other dev branches, and may get erratic behavior because of that.

(Maybe strike the reference to hot-fixes? They should be really rare for us, hopefully.)

What does 
>Clear the **develop** branch to receive features for the next big release

mean? Is there something the user does to clear the dev branch, or does this describe the end result?

**Review by mccalluc — COMMENTED** [review]
see earlier comment in the thread.

**Comment by thinkh** [comment]
I'm fine with removing the hotfixes.

As for versions the author wrote following:
> To keep the changes made in the release branch, we need to merge those back into develop, though. 
> This step may well lead to a merge conflict (probably even, since we have changed the version number). If so, fix it and commit.

So you are right, @mccalluc. Merging the whole release branch back into the develop branch does not work or is error prone. So we should merge only bugfixes that are made in the release branch into the develop branch. Can we manage that?

Further quotes about release branches:

> The key moment to branch off a new release branch from develop is when develop (almost) reflects the desired state of the new release. At least all features that are targeted for the release-to-be-built must be merged in to develop at this point in time. All features targeted at future releases may not—they must wait until after the release branch is branched off.

> It is exactly at the start of a release branch that the upcoming release gets assigned a version number—not any earlier. Up until that moment, the develop branch reflected changes for the “next release”, but it is unclear whether that “next release” will eventually become 0.3 or 1.0, until the release branch is started. That decision is made on the start of the release branch and is carried out by the project’s rules on version number bumping.

**Comment by mccalluc** [comment]
> So we should merge only bugfixes that are made in the release branch into the develop branch. Can we manage that?

I think ultimately it comes to what is least confusing for the person trying to do the release, and how long the release branch will sit out there before being merged. If bugs were discovered during the release process, another approach might be to abandon that release branch, feature branch from dev to fix the problem, then try again to make a release branch.

This is the process Refinery is using, so it can work, but that's only one repo: with Phovea and the multiple repos I worry more that a scheme with this many branches would be too confusing -- but I don't want to block this either: if it works, great, and if not, it can be tweaked.

**Comment by thinkh** [comment]
Thanks for your insight to the Refinery release process. I suggest that we try it now like this and see how it works. We can adapt the process and modify the document it later.

**Pull request merged**
