### PR TITLE
Proposed responsibilties list

### PR DESCRIPTION
**Pull request by mccalluc**
@sgratzl / @cnobre / @thinkh / @mccalluc / @aaljuhani / @pkerpedjiev / @bikramkawan: 

Assignments not quite entirely arbitrary: I've put Sam as primary for the central repos, and Holger for the slightly more peripheral ones, but:

- Sam and Holger, feel free to demote yourselves, if you think for a particular project someone else could quickly grow into ownership.
- All: check your notification settings for your repos. 
- All: feel free to lump more of these together if there are logical groupings.
- All: feel free to list projects from Caleydo here... I just don't want to list all of those.

### CODE REVIEW

**Comment by sgratzl** [comment]
if possible, I don't wanna be the primary of the `phovea_importer`. It is a rather visual and simple component. I would split `phovea_vis` and `phovea_d3`. vis contains a bunch of visualizations. d3 d3 utils but also a lot about visual linking. `phovea_bundle_lib` is just a mashup of multiple other plugins and doesn't contain any code. 

Please also add: 
- phovea/phovea.github.io
- Caleydo/lineup.js
- Caleydo/targid_ppi
- Caleydo/taco + Caleydo/taco_server
- Caleydo/targid*
- sgratzl/lineup_demos
- Caleydo/stratomex_js
- Caleydo/domino_js

to discuss: 
- Caleydo/pathfinder
- Caleydo/vials

**Comment by thinkh** [comment]
I have less or no knowledge/insight in the following projects and like to give it someone else:
- phovea_security_flask 
- phovea_graph_dot
- Caleydo/pathfinder
- Caleydo/vials
- Caleydo/lineup.js (I can be backup)

**Comment by sgratzl** [comment]
In the end, we should integrate the list in the corresponding README.md files. Moreover, we have to clarify what duties a "project/repo owner" has.

**Comment by mstreit** [comment]
I can be the owner of targid repos. @thinkh can be the co-owner.

**Comment by sgratzl** [comment]
suggestions for duties: 

the primary and secondary owner own the repository as the name suggests. That includes: 
 * managing issues, like assigning labels, priorities
 * assigning issues to people (either themselves or ask others) 
 * merging pull requests (but not the own ones) and doing code reviews
 * responsible if the master branch build breaks
 * on demand by the `generator-phovea` team, run and check `yo phovea:update`
 * ensure code quality, including documentation, api-changes, ...
 * in the long run: releasing the repository

the secondary is the backup for the primary in cases of pull requests created by the primary, vacations, ...

**Comment by thinkh** [comment]
I updated the list according to Marc's and my last comments.

**Pull request merged**
